name: "My First action"

description: "I made this!"

inputs:
  Icons:
    description: "Display icons?"
    default: "false"

outputs:
  IconResult:
    description: "Icons or Fruits"
    value: ${{ steps.GetFruits.outputs.random-id }}

runs:
  using: "composite"
  steps: 
    - shell: pwsh
      id: GetFruits
      run: |
        Write-Output "::group::My Awesome Function!"
        Write-Output "::notice File=MommaScript.ps1::Running my awesome function using runner file!"
        Write-Output "::endgroup::"

        $i = switch (${{ inputs.Icons }}) {
          'false' {$false}
          Default {$true}
        }

        try {
          Write-Output "::Group::Trying to run stuff"
          $res = & $env:GITHUB_ACTION_PATH\MommaScript.ps1 -Icons:$i
          
          # Write to standard output
          Write-Output "::notice::Result: $($res -join ',')"
          Write-Output "::endgroup::"

          # Write to output variable - Used in combination with the output keyword.
          Write-Output "random-id=$($res -join ',')" >> $GITHUB_OUTPUT

          # Set environment variables - works in the same job
          "IconsOutput=$($res -join ',')" >> $env:GITHUB_ENV
        }
        catch {
          Write-Output "::error file=MommaScript.ps1::Failed to run MommaScript!"
        }

    - shell: pwsh
      id: RepeatFruits
      run: |
        Write-Output "From env: $($env:IconsOutput)"
        Write-Output "From output: $  ($env:IconsOutput)"
